### ISSUE TITLE
Ошибка во время установки

### ISSUE THREAD

**Issue by marshal81** [southbridgeio/redmine_2chat#14]
День добрый,
использую redmine + docker + [docker-compose.](https://github.com/sameersbn/docker-redmine)
для установки зависимостей добавил pre-install.sh в plugins:

```
apt-get update && apt-get upgrade -y

# install redmine_2chat dependencies
apt-get install -y ruby-sidekiq ruby-sidekiq-cron
apt-get install -y clang openssl zlibc gperf git cmake
CURRENT_DIR=$(pwd)
cd /home/redmine/redmine/vendor
git clone https://github.com/tdlib/td.git
mkdir -p td/build
cd td/build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cd "${CURRENT_DIR}"
```

во время деплоя получаю следующую ошибку:
```
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:348:in `rescue in establish_connection'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:331:in `establish_connection'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:99:in `block in connect'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:294:in `with_reconnect'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:98:in `connect'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:367:in `ensure_connected'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:222:in `block in process'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:307:in `logging'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:221:in `process'
/home/redmine/data/tmp/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis/client.rb:118:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis.rb:2068:in `block in hget'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis.rb:45:in `block in synchronize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis.rb:45:in `synchronize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/redis-4.0.2/lib/redis.rb:2067:in `hget'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-1.0.4/lib/sidekiq/cron/job.rb:357:in `block in status_from_redis'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:95:in `block in redis'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:92:in `redis'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-1.0.4/lib/sidekiq/cron/job.rb:356:in `status_from_redis'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-1.0.4/lib/sidekiq/cron/job.rb:275:in `initialize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-1.0.4/lib/sidekiq/cron/job.rb:244:in `new'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-1.0.4/lib/sidekiq/cron/job.rb:244:in `create'
/home/redmine/redmine/plugins/redmine_2chat/init.rb:35:in `<top (required)>'
```

я что-то неверно сконфигурил?

**Comment by funk-yourself** [comment]
Sidekiq использует redis для очереди задач. Нужно запустить redis.
