### ISSUE TITLE
rake aborted! LoadError: No such file to load -- /opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb

### ISSUE THREAD

**Issue by ZerooCool** [southbridgeio/redmine_2chat#21]
cd /opt/redmine
su - redmine
Saisir le mot de passe (redmine)
cd redmine-4.0-stable/
cd plugins/
wget https://github.com/centosadmin/redmine_2chat/archive/master.zip
unzip master.zip
rm master.zip
cd ..

source /opt/redmine/.rvm/scripts/rvm
rvm list gemsets
rvm use gemset ruby-2.4.5@redmine-4.0-stable
bundle install --without development test
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

**Une erreur est rencontrée ---->
rake aborted!
LoadError: No such file to load -- /opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb**

Redémarrer Apache2 ---->
service apache2 restart

_Le Redmine local ne s'affiche plus._
_Je supprime le dossier du plugin dans le répertoire plugins/_
_Le Redmine local s'affiche à nouveau._

My tutoriel for install Redmine with RVM and Debian Stable : https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian_avec_RVM

**Comment by ZerooCool** [comment]
I change the name to the folder :
redmine@vps:~/redmine-4.0-stable/plugins$ mv redmine_2chat/ redmine_bots/

redmine@vps:~/redmine-4.0-stable/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV=development 

```
rake aborted!
NameError: uninitialized constant Sidekiq
/opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb:34:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb:7:in `<top (required)>'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:175:in `block in load'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `each'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `load'
/opt/redmine/redmine-4.0-stable/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0-stable/config/environment.rb:14:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by ZerooCool** [comment]
With --trace

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=development --trace
(in /opt/redmine/redmine-4.0-stable)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Sidekiq
/opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb:34:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/opt/redmine/redmine-4.0-stable/plugins/redmine_bots/init.rb:7:in `<top (required)>'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:175:in `block in load'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `each'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `load'
/opt/redmine/redmine-4.0-stable/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:415:in `call'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `each'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `call'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0-stable/config/environment.rb:14:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/opt/redmine/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/rake:23:in `load'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/rake:23:in `<main>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by Luckyvb** [comment]
you need redmine_bots install first. its required Sidekiq.
After all will be install all will be ok. Tested at 4.1.1

Documentation for plugins install is poor :(

**Comment by ZerooCool** [comment]
Can you help, how to install Sidekiq ?

**Comment by Luckyvb** [comment]
- [plugin to monitor](https://github.com/ogom/redmine_sidekiq)
After you need to start as service look at  #22
My **redmine/config/sidekiq.yml**:
```
---
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - default
  - telegram
  - issue_chats

production:
  :concurrency: 25
staging:
  :concurrency: 15
```
- Install [redmine_bots](https://github.com/southbridgeio/redmine_bots)
- by [documentation](https://github.com/southbridgeio/redmine_bots/blob/master/README.md) you need compile [TDlib](https://github.com/tdlib/td). look [building steps](https://github.com/tdlib/td#building) in documentation:
```
1. git clone https://github.com/tdlib/td
2. mkdir build
3. cd build
4. cmake -DCMAKE_BUILD_TYPE=Release ..
5. cmake --build .
```
- **TDlib** It should be **placed** it in **redmine_root/vendor** or added to **ldconfig**.
`ln /usr/local/lib/lbtdjson.so.1.6.0 /opt/redmine/vendor/lbtdjson.so`
- [Register bot and configure **redmine_bots**](https://telegram.me/botfather)
- if registration problem: [\#51](https://github.com/southbridgeio/redmine_bots/issues/51#issuecomment-640572287)

**Comment by ZerooCool** [comment]
Hum.
Ok, thank you for your answer.
I add this to my wiki, but, i don't have test.
Later ...
It's not very easy.

I haven't looked what sidekiq is.
Generally, I don't like to install new tools, in addition to the initial tool I am looking to install.

I would have to test it, to find out whether or not I can actually install it.

https://wiki.visionduweb.fr/index.php?title=Obsol%C3%A8te_Plugins_de_chat_pour_Redmine#redmine_2chat

**Comment by Luckyvb** [comment]
add gem sidekiq

**Comment by ZerooCool** [comment]
Ok, I add your info to my notes and I test ASAP.
Thank you.

https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian#redmine_2chat
